INSERT INTO cidade (nome) VALUES ('São Paulo');
INSERT INTO cidade (nome) VALUES ('Rio de Janeiro');
INSERT INTO cidade (nome) VALUES ('Belo Horizonte');
INSERT INTO cidade (nome) VALUES ('Brasília');
INSERT INTO cidade (nome) VALUES ('Salvador');
INSERT INTO cidade (nome) VALUES ('Fortaleza');
INSERT INTO cidade (nome) VALUES ('Curitiba');
INSERT INTO cidade (nome) VALUES ('Manaus');
INSERT INTO cidade (nome) VALUES ('Recife');
INSERT INTO cidade (nome) VALUES ('Belém');
INSERT INTO cidade (nome) VALUES ('Porto Alegre');
INSERT INTO cidade (nome) VALUES ('Goiânia');
INSERT INTO cidade (nome) VALUES ('São Luís');
INSERT INTO cidade (nome) VALUES ('Maceió');
INSERT INTO cidade (nome) VALUES ('Natal');
INSERT INTO cidade (nome) VALUES ('Campo Grande');
INSERT INTO cidade (nome) VALUES ('Teresina');
INSERT INTO cidade (nome) VALUES ('João Pessoa');
INSERT INTO cidade (nome) VALUES ('Aracaju');
INSERT INTO cidade (nome) VALUES ('Florianópolis');
INSERT INTO cidade (nome) VALUES ('Cuiabá');
INSERT INTO cidade (nome) VALUES ('Macapá');
INSERT INTO cidade (nome) VALUES ('Rio Branco');
INSERT INTO cidade (nome) VALUES ('Palmas');
INSERT INTO cidade (nome) VALUES ('Boa Vista');
INSERT INTO cidade (nome) VALUES ('Porto Velho');
INSERT INTO cidade (nome) VALUES ('Vitória');
INSERT INTO cidade (nome) VALUES ('São José dos Campos');
INSERT INTO cidade (nome) VALUES ('Santos');
INSERT INTO cidade (nome) VALUES ('Campinas');
INSERT INTO cidade (nome) VALUES ('Sorocaba');
INSERT INTO cidade (nome) VALUES ('Uberlândia');
INSERT INTO cidade (nome) VALUES ('Contagem');
INSERT INTO cidade (nome) VALUES ('Juiz de Fora');
INSERT INTO cidade (nome) VALUES ('Niterói');
INSERT INTO cidade (nome) VALUES ('Petrópolis');
INSERT INTO cidade (nome) VALUES ('Volta Redonda');
INSERT INTO cidade (nome) VALUES ('Feira de Santana');
INSERT INTO cidade (nome) VALUES ('Vitória da Conquista');
INSERT INTO cidade (nome) VALUES ('Caxias do Sul');
INSERT INTO cidade (nome) VALUES ('Pelotas');
INSERT INTO cidade (nome) VALUES ('Joinville');
INSERT INTO cidade (nome) VALUES ('Blumenau');
INSERT INTO cidade (nome) VALUES ('Londrina');
INSERT INTO cidade (nome) VALUES ('Maringá');
INSERT INTO cidade (nome) VALUES ('Foz do Iguaçu');
INSERT INTO cidade (nome) VALUES ('Ribeirão Preto');
INSERT INTO cidade (nome) VALUES ('São José do Rio Preto');
INSERT INTO cidade (nome) VALUES ('Piracicaba');
INSERT INTO cidade (nome) VALUES ('Bauru');
INSERT INTO cidade (nome) VALUES ('Franca');
INSERT INTO cidade (nome) VALUES ('Taubaté');
INSERT INTO cidade (nome) VALUES ('Caruaru');
INSERT INTO cidade (nome) VALUES ('Campina Grande');
INSERT INTO cidade (nome) VALUES ('Ilhéus');
INSERT INTO cidade (nome) VALUES ('Itabuna');
INSERT INTO cidade (nome) VALUES ('Santa Maria');
INSERT INTO cidade (nome) VALUES ('Passo Fundo');
INSERT INTO cidade (nome) VALUES ('Cascavel');
INSERT INTO cidade (nome) VALUES ('Ponta Grossa');
INSERT INTO cidade (nome) VALUES ('Chapecó');
INSERT INTO cidade (nome) VALUES ('Lages');
INSERT INTO cidade (nome) VALUES ('Araraquara');
INSERT INTO cidade (nome) VALUES ('Barretos');
INSERT INTO cidade (nome) VALUES ('Jaú');
INSERT INTO cidade (nome) VALUES ('Limeira');
INSERT INTO cidade (nome) VALUES ('Presidente Prudente');
INSERT INTO cidade (nome) VALUES ('Votorantim');
INSERT INTO cidade (nome) VALUES ('Mogi das Cruzes');
INSERT INTO cidade (nome) VALUES ('Guarulhos');
INSERT INTO cidade (nome) VALUES ('Osasco');
INSERT INTO cidade (nome) VALUES ('São Bernardo do Campo');
INSERT INTO cidade (nome) VALUES ('Santo André');
INSERT INTO cidade (nome) VALUES ('Santos');
INSERT INTO cidade (nome) VALUES ('São Caetano do Sul');
INSERT INTO cidade (nome) VALUES ('Diadema');
INSERT INTO cidade (nome) VALUES ('Tatuí');
INSERT INTO cidade (nome) VALUES ('Itu');
INSERT INTO cidade (nome) VALUES ('Salto');
INSERT INTO cidade (nome) VALUES ('Indaiatuba');
INSERT INTO cidade (nome) VALUES ('Jundiaí');
